/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Point */

#ifndef _Included_com_tmax_symbol_treesitter_model_Point
#define _Included_com_tmax_symbol_treesitter_model_Point
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Point
 * Method:    compareTo
 * Signature: (Lch/usi/si/seart/treesitter/Point;)I
 */
JNIEXPORT jint JNICALL Java_com_tmax_symbol_treesitter_model_Point_compareTo
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
