/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Query */

#ifndef _Included_com_tmax_symbol_treesitter_model_Query
#define _Included_com_tmax_symbol_treesitter_model_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tmax_symbol_treesitter_model_Query_delete
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
