/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Language */

#ifndef _Included_com_tmax_symbol_treesitter_model_Language
#define _Included_com_tmax_symbol_treesitter_model_Language
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tmax_symbol_treesitter_model_Language_INVALID
#define com_tmax_symbol_treesitter_model_Language_INVALID 0LL
/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    c
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tmax_symbol_treesitter_model_Language_c
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    java
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tmax_symbol_treesitter_model_Language_java
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    python
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tmax_symbol_treesitter_model_Language_python
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    version
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tmax_symbol_treesitter_model_Language_version
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    symbols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tmax_symbol_treesitter_model_Language_symbols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    symbol
 * Signature: (JI)Lch/usi/si/seart/treesitter/Symbol;
 */
JNIEXPORT jobject JNICALL Java_com_tmax_symbol_treesitter_model_Language_symbol
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    fields
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tmax_symbol_treesitter_model_Language_fields
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
