/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Capture */

#ifndef _Included_com_tmax_symbol_treesitter_model_Capture
#define _Included_com_tmax_symbol_treesitter_model_Capture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Capture
 * Method:    disable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tmax_symbol_treesitter_model_Capture_disable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
